site_name: Systems Engineering Library (se-lib)
site_url: https://se-lib.org
site_description: Open source Python library for integrated systems modeling
site_author: se-lib Development Team

repo_url: https://github.com/se-lib/se-lib
repo_name: se-lib/se-lib
edit_uri: ""

# Define global variables
extra:
  repo_version: "jan_26"

theme:
  name: readthedocs
  logo: se-lib_banner.svg
  highlightjs: false
  custom_dir: overrides
  favicon: assets/favicon.ico

extra_css:
  - custom.css
  # with highlightjs
  # - vs.css
  # with pygments
  # - vs_pygments.css
  
plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      # below could be moot with noclasses: true
      pygments_lang_class: true
      # use inline styles not custom css classes
      noclasses: true
      pygments_style: vs
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables
  
nav:
  - Home: index.md
  - Installation: installation.md
  - Function Reference: function_reference.md
  - Examples: examples.md
  - Online:
      # - SysML Scratchpad here top level: scratchpad.md
      - SysML Scratchpad: online/scratchpad.md
      - Discrete Event Modeling Demonstrations: https://se-lib.org/online/discrete_event_modeling_demo.html
      - se-lib playground: https://se-lib.org/online/sysml.html
  - AI chatbots:
    - se-lib chatbot: https://se-lib.org/ai/ai.html
    - se-lib chatbot2: chatbot.md
  - Tutorials:
      - Tutorials: https://se-lib.org/tutorials/sd_incose.html
  - Manuals:
      - System Dynamics Simulation: https://colab.research.google.com/drive/1oE5TBdF-hpJTQbQgSmPgmPoofBgOTR0B?usp=sharing
      - Discrete Event Simulation: https://colab.research.google.com/drive/1arDDaaltEyGLomaGo5ZKVumtviloUAyG?usp=sharing
      
copyright: Copyright &copy; 2026 se-lib Development Team
