site_name: Systems Engineering Library (se-lib)
site_url: https://se-lib.org
site_description: Open source Python library for integrated systems modeling
site_author: se-lib Development Team

repo_url: https://github.com/se-lib/se-lib
repo_name: se-lib/se-lib
edit_uri: ""

theme:
  name: readthedocs
  logo: se-lib_banner.svg
  highlightjs: true
  custom_dir: overrides

extra_css:
  - custom.css
  - vs.css
  
plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - tables
  
nav:
  - Home: index.md
  - Installation: installation.md
  - Function Reference: function_reference.md
  - Examples: examples.md
  - Online:
      - SysML Scratchpad: https://se-lib.org/online/scratchpad.html
      - Discrete Event Modeling Demonstrations: https://se-lib.org/online/discrete_event_modeling_demo.html
      - se-lib playground: https://se-lib.org/online/sysml.html
  - Tutorials:
      - Tutorials: https://se-lib.org/tutorials/sd_incose.html
  - Manuals:
      - System Dynamics Simulation: https://colab.research.google.com/drive/1oE5TBdF-hpJTQbQgSmPgmPoofBgOTR0B?usp=sharing
      - Discrete Event Simulation: https://colab.research.google.com/drive/1arDDaaltEyGLomaGo5ZKVumtviloUAyG?usp=sharing
      
copyright: Copyright &copy; 2025 se-lib Development Team
